/* =========================================================================
   Arena — catalogue & site content
   ========================================================================= */
(function () {
  'use strict';
  /* gate scroll-reveal styles: without JS the content must stay visible */
  document.documentElement.classList?.add('js');

  const R = (id) => `assets/products/${id}.svg`;

  const categories = [
    {
      id: 'audio',
      name: 'Audio',
      short: 'Headphones & speakers',
      blurb: 'Headphones, earbuds and speakers tuned for long, quiet listening.',
      image: 'assets/img/mesh.jpg',
      hero: R('halo-one'),
    },
    {
      id: 'workspace',
      name: 'Workspace',
      short: 'Keyboards & lighting',
      blurb: 'Input, light and power for a desk that stays out of your way.',
      image: 'assets/img/desk-flatlay.jpg',
      hero: R('slate65'),
    },
    {
      id: 'everyday',
      name: 'Everyday',
      short: 'Wearables & carry',
      blurb: 'Wearables and carry goods built to outlive the trend cycle.',
      image: 'assets/img/wall.jpg',
      hero: R('meridian-watch'),
    },
  ];

  const products = [
    {
      id: 'halo-one',
      name: 'Halo One',
      category: 'audio',
      price: 34900,
      compareAt: 39900,
      rating: 4.9,
      reviews: 412,
      badge: 'Bestseller',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
        { name: 'Clay', hex: '#c07a5c' },
      ],
      tagline: 'Reference over-ear headphones',
      blurb:
        'Forty millimetre bio-cellulose drivers, adaptive noise cancellation and a magnesium frame that disappears on your head after ten minutes.',
      details: [
        'Halo One was tuned in our Copenhagen acoustic lab across 1,400 hours of listening sessions — classical, jazz, and the commuter’s commute. The result is a neutral, unhurried signature with bass that stays polite until you ask for it.',
        'Adaptive cancellation reads the room 48,000 times a second and adjusts without the vacuum feeling. Temple-free controls: a light tap, a firm press, a turn.',
      ],
      specs: {
        Drivers: '40 mm bio-cellulose',
        Battery: '60 h (ANC on), 10 min = 8 h',
        Materials: 'Magnesium, protein leather, wool felt',
        Weight: '268 g',
        Connection: 'Bluetooth 5.4, LDAC, USB-C',
        'In the box': 'Case, 3.5 mm cable, USB-C cable',
      },
      image: R('halo-one'),
      gallery: [
        { src: R('halo-one'), pos: 'center', scale: 1.12 },
        { src: R('halo-one'), pos: '30% 34%', scale: 1.7 },
        { src: 'assets/img/mesh.jpg', pos: 'center', scale: 1.12 },
        { src: R('halo-one'), pos: '72% 68%', scale: 1.7 },
      ],
    },
    {
      id: 'halo-buds',
      name: 'Halo Buds',
      category: 'audio',
      price: 19900,
      compareAt: null,
      rating: 4.8,
      reviews: 267,
      badge: 'New',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
      ],
      tagline: 'True wireless, transparent by design',
      blurb:
        'A featherweight stem, a case milled from a single billet, and transparency mode so natural you will forget you are wearing them.',
      details: [
        'Six microphones handle calls in crosswind; the rest handle you. Halo Buds pair in under a second and hold a connection through a crowded platform.',
        'The case charges three full cycles before it wants a cable, and the whole assembly is serviceable — batteries are replaceable, not permanent.',
      ],
      specs: {
        Drivers: '11 mm dynamic',
        Battery: '9 h buds, 36 h with case',
        Materials: 'Recycled aluminium, bio-resin',
        Weight: '4.9 g per bud',
        Connection: 'Bluetooth 5.4, LE Audio',
        Rating: 'IPX5',
      },
      image: R('halo-buds'),
      gallery: [
        { src: R('halo-buds'), pos: 'center', scale: 1.12 },
        { src: R('halo-buds'), pos: '38% 30%', scale: 1.8 },
        { src: 'assets/img/flatlay.jpg', pos: 'center', scale: 1.12 },
        { src: R('halo-buds'), pos: '58% 70%', scale: 1.7 },
      ],
    },
    {
      id: 'monolith-s',
      name: 'Monolith S',
      category: 'audio',
      price: 44900,
      compareAt: null,
      rating: 4.9,
      reviews: 158,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'Portable speaker, room-filling',
      blurb:
        'One solid column of sound: passive radiators top and bottom, a machined dial on top, and enough body to fill a room without a corner to lean on.',
      details: [
        'Monolith S uses a coaxial pair of drivers aimed at each other to cancel vibration, so the cabinet stays still and the music does not.',
        'Wi-Fi and Bluetooth share one device profile — pick up where you left off on either, without re-pairing anything.',
      ],
      specs: {
        Output: '120 W Class-D',
        Battery: '24 h at half volume',
        Materials: 'Anodised aluminium, acoustic mesh',
        Weight: '2.4 kg',
        Connection: 'Wi-Fi 6, Bluetooth 5.4, AirPlay',
        Inputs: 'USB-C, 3.5 mm',
      },
      image: R('monolith-s'),
      gallery: [
        { src: R('monolith-s'), pos: 'center', scale: 1.12 },
        { src: R('monolith-s'), pos: '50% 34%', scale: 1.7 },
        { src: 'assets/img/mesh.jpg', pos: '60% 40%', scale: 1.2 },
        { src: R('monolith-s'), pos: '50% 76%', scale: 1.6 },
      ],
    },
    {
      id: 'drift-speaker',
      name: 'Drift Speaker',
      category: 'audio',
      price: 22900,
      compareAt: null,
      rating: 4.8,
      reviews: 154,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
        { name: 'Moss', hex: '#6f7a63' },
      ],
      tagline: 'Portable speaker, weatherproof',
      blurb:
        'A fabric-wrapped cylinder with a carry strap, thirty hours of battery and enough low end to fill a kitchen without shaking the shelves.',
      details: [
        'Drift pairs in one step and remembers the last three devices. Set two of them within a metre of each other and they become a stereo pair — no app, no account, no firmware screen.',
        'The shell is IP67, so rain, sand and an accidental sink are all survivable. The strap unbolts for replacement, and the battery is a published part after year seven.',
      ],
      specs: {
        Output: '40 W, dual passive radiators',
        Battery: '30 h at half volume',
        Rating: 'IP67',
        Materials: 'Recycled PBT fabric, silicone',
        Weight: '640 g',
        Connection: 'BT 5.4, LE Audio, Auracast',
      },
      image: R('drift-speaker'),
      gallery: [
        { src: R('drift-speaker'), pos: 'center', scale: 1.12 },
        { src: R('drift-speaker'), pos: '40% 46%', scale: 1.8 },
        { src: 'assets/img/mesh.jpg', pos: '30% 50%', scale: 1.3 },
        { src: R('drift-speaker'), pos: '62% 58%', scale: 1.7 },
      ],
    },
    {
      id: 'signal-amp',
      name: 'Signal Amp',
      category: 'audio',
      price: 32900,
      compareAt: null,
      rating: 4.7,
      reviews: 88,
      badge: null,
      stock: 4,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
      ],
      tagline: 'Desktop amplifier, fully analog',
      blurb:
        'One input, one output, one machined volume dial. Two quiet watts into whatever headphones you already own — no menu, no app, no firmware.',
      details: [
        'Signal is class-A through the first stage and DC-coupled at the output, so it stays out of the way of the recording. The dial is turned from solid aluminium and weighted to move slowly.',
        'The front jack senses what you plug in and sets gain accordingly; the rear takes USB-C or line in. Every component on the board is a published part we stock for seven years.',
      ],
      specs: {
        Output: '2 W into 32 Ω, class-A',
        'Noise floor': '< −118 dBV',
        Inputs: 'USB-C, 3.5 mm line',
        Materials: 'CNC aluminium, steel',
        Weight: '780 g',
        'In the box': 'USB-C cable, 6.3 mm adapter',
      },
      image: R('signal-amp'),
      gallery: [
        { src: R('signal-amp'), pos: 'center', scale: 1.12 },
        { src: R('signal-amp'), pos: '50% 55%', scale: 1.9 },
        { src: 'assets/img/desk-flatlay.jpg', pos: '50% 40%', scale: 1.3 },
        { src: R('signal-amp'), pos: '34% 40%', scale: 1.7 },
      ],
    },
    {
      id: 'slate65',
      name: 'Slate 65',
      category: 'workspace',
      price: 22900,
      compareAt: null,
      rating: 4.9,
      reviews: 331,
      badge: 'Bestseller',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
        { name: 'Moss', hex: '#6f7a63' },
      ],
      tagline: 'Low-profile mechanical keyboard',
      blurb:
        'Sixty-five keys, gasket-mounted, tuned to a soft bottom-out. It sounds like rain on a desk and types like nothing at all.',
      details: [
        'Slate 65 uses a two-piece case with a silicone gasket layer, so every keystroke lands on suspension rather than on your desk.',
        'Hot-swappable switches, three-device memory, and a keycap set dye-sublimated to stay legible for a decade.',
      ],
      specs: {
        Layout: '65%, ANSI / ISO',
        Switches: 'Linear 45 g, hot-swappable',
        Battery: '90 h backlight off',
        Materials: 'CNC aluminium, PBT keycaps',
        Weight: '1.1 kg',
        Connection: 'USB-C, BT 5.3, 2.4 GHz',
      },
      image: R('slate65'),
      gallery: [
        { src: R('slate65'), pos: 'center', scale: 1.12 },
        { src: R('slate65'), pos: '30% 52%', scale: 1.8 },
        { src: 'assets/img/desk-flatlay.jpg', pos: 'center', scale: 1.12 },
        { src: R('slate65'), pos: '70% 58%', scale: 1.7 },
      ],
    },
    {
      id: 'arc-mouse',
      name: 'Arc Mouse',
      category: 'workspace',
      price: 12900,
      compareAt: null,
      rating: 4.7,
      reviews: 204,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
      ],
      tagline: 'Silent, sculpted, all-day',
      blurb:
        'A single continuous shell with a machined scroll wheel. Silent switches, 8,000 DPI, and a shape that agrees with your hand by lunchtime.',
      details: [
        'The shell is one piece, so there is nothing to creak. The wheel is turned from solid brass and anodised to match.',
        'Switches are rated for 60 million clicks and can be replaced in four minutes with a T5 driver.',
      ],
      specs: {
        Sensor: '8,000 DPI optical',
        Battery: '70 days',
        Materials: 'Recycled PC, anodised aluminium',
        Weight: '78 g',
        Buttons: '6, programmable',
        Connection: 'BT 5.3, 2.4 GHz',
      },
      image: R('arc-mouse'),
      gallery: [
        { src: R('arc-mouse'), pos: 'center', scale: 1.12 },
        { src: R('arc-mouse'), pos: '50% 38%', scale: 1.8 },
        { src: 'assets/img/desk-flatlay.jpg', pos: '30% 60%', scale: 1.3 },
        { src: R('arc-mouse'), pos: '50% 74%', scale: 1.6 },
      ],
    },
    {
      id: 'lumen-desk',
      name: 'Lumen Desk Lamp',
      category: 'workspace',
      price: 27900,
      compareAt: null,
      rating: 4.8,
      reviews: 96,
      badge: 'New',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
      ],
      tagline: 'Task light that respects the room',
      blurb:
        'A counterweighted arm, a warm-to-cool LED array, and a dial that remembers the last light you loved.',
      details: [
        'Lumen renders colour at 97 CRI, so drawings, food and faces all look like themselves after dark.',
        'The joint holds any position without a screw, and the head stays cool enough to adjust mid-sentence.',
      ],
      specs: {
        Output: '820 lm, flicker-free',
        Temperature: '2,200 K – 5,000 K',
        'Colour accuracy': '97 CRI',
        Materials: 'Steel, aluminium, marble base',
        Weight: '3.1 kg',
        Power: 'USB-C PD, 30 W',
      },
      image: R('lumen-desk'),
      gallery: [
        { src: R('lumen-desk'), pos: 'center', scale: 1.12 },
        { src: R('lumen-desk'), pos: '58% 44%', scale: 1.8 },
        { src: 'assets/img/leaf-shadow.jpg', pos: 'center', scale: 1.2 },
        { src: R('lumen-desk'), pos: '44% 76%', scale: 1.6 },
      ],
    },
    {
      id: 'dock-one',
      name: 'Dock One',
      category: 'workspace',
      price: 14900,
      compareAt: null,
      rating: 4.6,
      reviews: 142,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'The end of the cable pile',
      blurb:
        'A weighted stand that charges phone, watch and buds at once — and folds flat when the working day is over.',
      details: [
        'Three coils, one transformer. Dock One negotiates power so everything fills at its own rate without heat to spare.',
        'The upright folds to 18 mm, so it disappears into a laptop sleeve between home and studio.',
      ],
      specs: {
        Output: '15 W + 5 W + 5 W',
        Materials: 'Aluminium, silicone, walnut',
        Weight: '460 g',
        Folded: '18 mm',
        'In the box': '100 W GaN adapter, 1.5 m cable',
        Warranty: '2 years',
      },
      image: R('dock-one'),
      gallery: [
        { src: R('dock-one'), pos: 'center', scale: 1.12 },
        { src: R('dock-one'), pos: '50% 62%', scale: 1.8 },
        { src: 'assets/img/desk-flatlay.jpg', pos: '70% 30%', scale: 1.3 },
        { src: R('dock-one'), pos: '40% 30%', scale: 1.6 },
      ],
    },
    {
      id: 'beam-bar',
      name: 'Beam Screen Bar',
      category: 'workspace',
      price: 14900,
      compareAt: 17900,
      rating: 4.8,
      reviews: 112,
      badge: 'New',
      colors: [{ name: 'Graphite', hex: '#2b2b30' }],
      tagline: 'Monitor light, zero glare',
      blurb:
        'An asymmetrical lens throws light onto the desk and none onto the screen, with an ambient sensor that adjusts itself and then gets out of the way.',
      details: [
        'Beam mounts on any monitor 6–32 mm thick with a counterweighted clip — no adhesive, no wobble. The hinge aims the cut-off line to the millimetre.',
        'Light runs at 97 CRI from 2,700 to 6,000 K. The dial remembers your last setting and there is nothing else to learn.',
      ],
      specs: {
        Output: '700 lm, flicker-free',
        Temperature: '2,700 K – 6,000 K',
        'Colour accuracy': '97 CRI',
        Sensors: 'Ambient light, auto-dim',
        Materials: 'Aluminium, optical PC',
        Power: 'USB-C, 6 W',
      },
      image: R('beam-bar'),
      gallery: [
        { src: R('beam-bar'), pos: 'center', scale: 1.12 },
        { src: R('beam-bar'), pos: '50% 40%', scale: 1.8 },
        { src: 'assets/img/leaf-shadow.jpg', pos: '40% 60%', scale: 1.3 },
        { src: R('beam-bar'), pos: '50% 64%', scale: 1.7 },
      ],
    },
    {
      id: 'contour-mat',
      name: 'Contour Desk Mat',
      category: 'workspace',
      price: 6900,
      compareAt: null,
      rating: 4.7,
      reviews: 176,
      badge: null,
      stock: 0,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Sand', hex: '#d9cfc0' },
        { name: 'Moss', hex: '#6f7a63' },
      ],
      tagline: 'Wool felt, stitched edges',
      blurb:
        'Four millimetres of pressed wool under keyboard and mouse, with a silicone base that refuses to slide and edges stitched to outlast the desk.',
      details: [
        'Contour is die-cut from a single sheet of 4 mm wool felt — dense enough for a steady mouse, soft enough for a resting wrist.',
        'The felt is 100% wool with no backing to peel, and it is washable. The stitching is the same thread we use on Atlas packs.',
      ],
      specs: {
        Size: '80 × 40 × 0.4 cm',
        Materials: '100% wool felt, silicone base',
        Weight: '520 g',
        Edge: 'Lockstitched, 4 colours',
        Care: 'Hand wash, air dry',
        Warranty: '5 years',
      },
      image: R('contour-mat'),
      gallery: [
        { src: R('contour-mat'), pos: 'center', scale: 1.12 },
        { src: R('contour-mat'), pos: '50% 58%', scale: 1.8 },
        { src: 'assets/img/desk-flatlay.jpg', pos: '60% 60%', scale: 1.4 },
        { src: R('contour-mat'), pos: '36% 40%', scale: 1.7 },
      ],
    },
    {
      id: 'meridian-watch',
      name: 'Meridian 38',
      category: 'everyday',
      price: 49900,
      compareAt: 56000,
      rating: 4.9,
      reviews: 188,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
        { name: 'Clay', hex: '#c07a5c' },
      ],
      tagline: 'Automatic, 38 mm, no fuss',
      blurb:
        'A three-hand automatic with a sector dial, sapphire crystal and a strap that softens to your wrist in a week.',
      details: [
        'The movement is wound by motion — no battery, no charging, no ceremony. It keeps time to +4 seconds a day or better.',
        'The case is 38 mm across and 9.4 mm tall, so it sits under a cuff and against a desk without complaint.',
      ],
      specs: {
        Movement: 'Automatic, 38 h reserve',
        Accuracy: '+4 / −4 s per day',
        Case: '316L steel, 38 mm × 9.4 mm',
        Crystal: 'Sapphire, AR-coated',
        'Water resistance': '10 ATM',
        Strap: 'Quick-release, 20 mm',
      },
      image: R('meridian-watch'),
      gallery: [
        { src: R('meridian-watch'), pos: 'center', scale: 1.12 },
        { src: R('meridian-watch'), pos: '50% 46%', scale: 1.9 },
        { src: 'assets/img/wall.jpg', pos: 'center', scale: 1.2 },
        { src: R('meridian-watch'), pos: '50% 74%', scale: 1.7 },
      ],
    },
    {
      id: 'atlas-pack',
      name: 'Atlas Pack 22L',
      category: 'everyday',
      price: 25900,
      compareAt: null,
      rating: 4.8,
      reviews: 273,
      badge: 'New',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Moss', hex: '#6f7a63' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'Twenty-two litres, nothing wasted',
      blurb:
        'A clamshell pack in recycled ripstop with a suspended laptop sleeve, luggage pass-through and zips you can yank.',
      details: [
        'Atlas opens flat like a case, so packing is a decision instead of a dig. The laptop sleeve floats 12 mm off the ground.',
        'Every seam is bar-tacked and every zip is YKK Aquaguard — the bag is warrantied for a decade of daily carry.',
      ],
      specs: {
        Volume: '22 L',
        'Laptop': 'Up to 16″, suspended',
        Materials: 'Recycled 420D ripstop, DWR',
        Weight: '1.1 kg',
        Zips: 'YKK Aquaguard',
        Warranty: '10 years',
      },
      image: R('atlas-pack'),
      gallery: [
        { src: R('atlas-pack'), pos: 'center', scale: 1.12 },
        { src: R('atlas-pack'), pos: '50% 38%', scale: 1.7 },
        { src: 'assets/img/stairs.jpg', pos: 'center', scale: 1.2 },
        { src: R('atlas-pack'), pos: '50% 72%', scale: 1.6 },
      ],
    },
    {
      id: 'field-bottle',
      name: 'Field Bottle 600',
      category: 'everyday',
      price: 5900,
      compareAt: null,
      rating: 4.9,
      reviews: 612,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Chalk', hex: '#ebe8e1' },
        { name: 'Moss', hex: '#6f7a63' },
        { name: 'Clay', hex: '#c07a5c' },
      ],
      tagline: 'Cold for 24 hours',
      blurb:
        'Double-walled steel, a powder coat that resists bags and desks, and a cap you can open with one hand on a bike.',
      details: [
        'Vacuum insulation holds 4 °C for a day and 60 °C for twelve hours, with no condensation on the outside.',
        'The threads are standard, so the cap, sport top and filter all interchange across the Field range.',
      ],
      specs: {
        Capacity: '600 ml',
        Insulation: '24 h cold, 12 h hot',
        Materials: '18/8 stainless, powder coat',
        Weight: '310 g',
        'Lid': 'One-hand flip, dishwasher safe',
        Fittings: 'Standard 48 mm thread',
      },
      image: R('field-bottle'),
      gallery: [
        { src: R('field-bottle'), pos: 'center', scale: 1.12 },
        { src: R('field-bottle'), pos: '50% 32%', scale: 1.8 },
        { src: 'assets/img/wall.jpg', pos: '30% 60%', scale: 1.3 },
        { src: R('field-bottle'), pos: '50% 72%', scale: 1.6 },
      ],
    },
    {
      id: 'prism-shades',
      name: 'Prism Shades',
      category: 'everyday',
      price: 18900,
      compareAt: null,
      rating: 4.7,
      reviews: 121,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'Italian acetate, polarised glass',
      blurb:
        'A softened square in bio-acetate with mineral lenses that cut glare without turning the world grey.',
      details: [
        'The frame is cut from a single block of Mazzucchelli acetate and tumbled for five days until it feels like sea glass.',
        'Lenses are mineral, polarised and hard-coated — scratch-resistant, and replaceable at any optician.',
      ],
      specs: {
        Lens: 'Mineral, polarised, category 3',
        Frame: 'Bio-acetate, 47–21–145',
        Protection: '100% UVA / UVB',
        Weight: '28 g',
        Hinges: 'Five-barrel, stainless',
        'In the box': 'Case, cloth, pouch',
      },
      image: R('prism-shades'),
      gallery: [
        { src: R('prism-shades'), pos: 'center', scale: 1.12 },
        { src: R('prism-shades'), pos: '34% 52%', scale: 1.9 },
        { src: 'assets/img/leaf-shadow.jpg', pos: '60% 40%', scale: 1.3 },
        { src: R('prism-shades'), pos: '68% 54%', scale: 1.8 },
      ],
    },
    {
      id: 'orbit-cam',
      name: 'Orbit 35',
      category: 'everyday',
      price: 129900,
      compareAt: null,
      rating: 5.0,
      reviews: 47,
      badge: 'Made to order',
      fulfilment: 'made-to-order',
      colors: [{ name: 'Graphite', hex: '#2b2b30' }],
      tagline: 'Compact 35 mm rangefinder',
      blurb:
        'A mechanical camera with a 40 mm f/2 lens, a quiet leaf shutter and dials that do exactly what they say.',
      details: [
        'Orbit 35 is assembled by hand in our Copenhagen workshop to order, then serialised and tested against a chart before it ships.',
        'Metering is aperture-priority or fully manual; everything else is a decision you make with your fingers.',
      ],
      specs: {
        Lens: '40 mm f/2, 6 elements',
        Shutter: 'Leaf, 1/500 – 1 s + B',
        Metering: 'Aperture priority, manual',
        Film: '35 mm, DX or manual',
        Body: 'Magnesium, leatherette',
        Weight: '498 g',
      },
      image: R('orbit-cam'),
      gallery: [
        { src: R('orbit-cam'), pos: 'center', scale: 1.12 },
        { src: R('orbit-cam'), pos: '50% 56%', scale: 1.9 },
        { src: 'assets/img/flatlay.jpg', pos: '40% 40%', scale: 1.3 },
        { src: R('orbit-cam'), pos: '30% 30%', scale: 1.7 },
      ],
    },
    {
      id: 'cairn-wallet',
      name: 'Cairn Wallet',
      category: 'everyday',
      price: 8900,
      compareAt: null,
      rating: 4.8,
      reviews: 231,
      badge: null,
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Clay', hex: '#c07a5c' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'Four cards, no bulk',
      blurb:
        'A folded cardholder in vegetable-tanned leather that holds what you carry and nothing you do not — and darkens into your own map of routes.',
      details: [
        'One piece of leather, four stitches per corner, no lining to tear. Cards sit at an angle, so the one you want is always the one you see.',
        'The leather is tanned without chrome and finished without plastic, so it scratches honestly and heals with a thumb.',
      ],
      specs: {
        Capacity: '4 cards, folded notes',
        Materials: 'Vegetable-tanned leather',
        Weight: '38 g',
        Dimensions: '10.5 × 7.2 × 0.8 cm',
        Thread: 'Waxed linen',
        Warranty: '10 years',
      },
      image: R('cairn-wallet'),
      gallery: [
        { src: R('cairn-wallet'), pos: 'center', scale: 1.12 },
        { src: R('cairn-wallet'), pos: '50% 46%', scale: 1.9 },
        { src: 'assets/img/flatlay.jpg', pos: '60% 40%', scale: 1.3 },
        { src: R('cairn-wallet'), pos: '40% 66%', scale: 1.7 },
      ],
    },
    {
      id: 'atlas-tote',
      name: 'Atlas Tote 14L',
      category: 'everyday',
      price: 17900,
      compareAt: null,
      rating: 4.7,
      reviews: 64,
      badge: 'New',
      colors: [
        { name: 'Graphite', hex: '#2b2b30' },
        { name: 'Moss', hex: '#6f7a63' },
        { name: 'Sand', hex: '#d9cfc0' },
      ],
      tagline: 'Fourteen litres, stands open',
      blurb:
        'The Atlas fabric and hardware, cut into a tote that stands on the floor instead of collapsing into it — with a laptop sleeve that keeps its shape.',
      details: [
        'A wire frame in the rim holds the mouth open, so loading takes two hands at most and finding your keys is a glance, not a dig.',
        'The straps are bar-tacked and rated to 20 kg; the base is a doubled panel of the same ripstop we warrant on the pack for a decade.',
      ],
      specs: {
        Volume: '14 L',
        Laptop: 'Up to 13″, suspended',
        Materials: 'Recycled 420D ripstop, DWR',
        Weight: '620 g',
        Straps: 'Bar-tacked, 20 kg rated',
        Warranty: '10 years',
      },
      image: R('atlas-tote'),
      gallery: [
        { src: R('atlas-tote'), pos: 'center', scale: 1.12 },
        { src: R('atlas-tote'), pos: '50% 40%', scale: 1.7 },
        { src: 'assets/img/stairs.jpg', pos: '50% 50%', scale: 1.3 },
        { src: R('atlas-tote'), pos: '50% 70%', scale: 1.6 },
      ],
    },
  ];

  const press = ['WIRED', 'Monocle', 'Dezeen', 'Fast Company', 'Wallpaper*', 'The Verge', 'Kinfolk'];

  const testimonials = [
    {
      text:
        'I bought the Halo One expecting another pair of headphones. Two years later it is the only object in my flat I would replace with the exact same thing.',
      name: 'Marta Lindqvist',
      role: 'Architect, Stockholm',
      initials: 'ML',
      rating: 5,
    },
    {
      text:
        'The Slate 65 arrived with a handwritten card and a spare set of switches. It is the quietest keyboard I own and the only one I have not modified.',
      name: 'Daniel Okafor',
      role: 'Staff engineer, Berlin',
      initials: 'DO',
      rating: 5,
    },
    {
      text:
        'Everything about Arena feels deliberate — the packaging, the weight, the way the case closes. Nothing is loud, and nothing is cheap.',
      name: 'Yuki Tanaka',
      role: 'Creative director, Kyoto',
      initials: 'YT',
      rating: 5,
    },
  ];

  const journal = [
    {
      slug: 'designed-to-be-repaired',
      title: 'Designed to be repaired, not replaced',
      excerpt: 'Why every Arena product opens with a single driver — and what that changes about the way we design.',
      date: '12 Mar 2026',
      read: '6 min',
      image: 'assets/img/desk-flatlay.jpg',
      tag: 'Craft',
      body: [
        'Every object we ship opens with the same T5 driver. Not because it is charming marketing, but because a fastener is a promise: if you can see the screw, you are allowed inside. The alternative — glue, welds, ultrasonic welds, potted boards — is a decision that the object ends at its first fault.',
        'The discipline starts earlier than the screw, though. A product that can be opened also has to be worth opening: parts must be orderable, diagrams published, and the person repairing it in 2033 has to find both. We keep a parts inventory for a minimum of seven years after a product is discontinued, and the repair guides live in the box, not behind a login.',
        'Designing this way changes the drawing. Seams sit where a tool naturally reaches. Batteries disconnect instead of dangling. Boards are labelled in plain language, because the person reading them at midnight is our customer, not our factory. Repairability is not a feature we add at the end; it is the constraint we design inside.',
        'There is a commercial argument too — repaired objects stay in use, owners come back for parts instead of replacements, and nothing we made ends up shredded. But honestly, the real reason is simpler: we would rather build the thing we would want to fix.',
      ],
    },
    {
      slug: 'inside-the-acoustic-lab',
      title: 'Inside the Copenhagen acoustic lab',
      excerpt: 'Fourteen hundred hours, one target curve, and an argument about two hundred hertz that lasted a month.',
      date: '28 Feb 2026',
      read: '9 min',
      image: 'assets/img/mesh.jpg',
      tag: 'Behind the scenes',
      body: [
        'The lab is one room in the studio with too much absorption on the walls and a strange habit of being coldest in the morning — which matters, because driver suspension stiffens slightly when it is cold, and a curve measured at 8 am is not the curve you hear at 8 pm.',
        'Halo One took 1,400 hours of listening across classical, jazz, and recordings of actual commutes. We tuned to a deliberately neutral target: bass that stays polite until the recording asks for it, and a top end that does not add shimmer to things that have none.',
        'The month-long argument was about 200 Hz. One of us heard a smear in string quartets; the rest of us heard nothing. It turned out to be a resonance in the ear-cup vent, three millimetres of extra felt behind it fixed it, and we have since made that felt a stocked spare part, because anything we tuned once we can retune forever.',
      ],
    },
    {
      slug: 'a-quieter-kind-of-luxury',
      title: 'A quieter kind of luxury',
      excerpt: 'The case for objects that whisper: material honesty, restrained colour, and the value of empty space.',
      date: '04 Feb 2026',
      read: '5 min',
      image: 'assets/img/leaf-shadow.jpg',
      tag: 'Point of view',
      body: [
        'Most objects are designed to be chosen and then apologised for. Loud logos, surfaces that photograph better than they feel, finishes that look new precisely because they will never be old. We are interested in the opposite trade: objects that look plain and age well.',
        'Material honesty is the rule. Aluminium looks like aluminium, felt like felt, leather like leather. Nothing is painted to imitate something it is not, because paint is the first thing to fail and the hardest thing to forgive.',
        'The last part is empty space. A product that does not beg for attention leaves room for the work on your desk and the music in your ears. We think that restraint is what people mean when they say something feels expensive — not the price, the quiet.',
      ],
    },
  ];

  const faqs = [
    {
      q: 'Where do you ship, and how fast?',
      a: 'We ship worldwide from Copenhagen and Rotterdam. Express orders placed before 14:00 CET arrive in 1–2 business days in the EU, 2–4 days to the UK and US. Standard shipping is free above $150.',
    },
    {
      q: 'What is your return policy?',
      a: 'Sixty nights, no questions. If an object is not right for you, print the prepaid label in your account and send it back — we refund to the original payment method within three business days of arrival.',
    },
    {
      q: 'Is anything user-serviceable?',
      a: 'Yes — all of it. Batteries, ear pads, switches, straps and zips are replaceable parts, and every product ships with a repair guide. We stock parts for a minimum of seven years after discontinuation.',
    },
    {
      q: 'Do you offer a warranty?',
      a: 'Two years on everything, ten years on Atlas packs, and lifetime repair support at cost for the original owner. Commercial and studio customers can extend coverage to five years at checkout.',
    },
  ];

  const perks = [
    { icon: 'truck', title: 'Free shipping', text: 'Standard delivery on orders over $150, worldwide.' },
    { icon: 'refresh', title: '60-night trial', text: 'Live with it two months. Return it free.' },
  ];

  const reviews = [
    {
      name: 'Sofia R.',
      initials: 'SR',
      date: '2 weeks ago',
      rating: 5,
      text: 'Arrived in two days, packed better than anything I have bought this year. The details in the listing were accurate down to the weight.',
    },
    {
      name: 'Marcus T.',
      initials: 'MT',
      date: '1 month ago',
      rating: 5,
      text: 'Third product from Arena. The consistency is the point — everything feels like it came from the same hand.',
    },
    {
      name: 'Elena P.',
      initials: 'EP',
      date: '1 month ago',
      rating: 4,
      text: 'Beautiful object and genuinely quiet in use. I would like one more colour option, but that is the only complaint I have.',
    },
  ];

  window.DATA = {
    brand: 'Arena',
    categories,
    products,
    press,
    testimonials,
    journal,
    faqs,
    perks,
    reviews,
    currency: 'USD',
    freeShipThreshold: 15000,
    expressFee: 1800,
    taxRate: 0.08,
    promoCodes: { ARENA10: 0.1, WELCOME15: 0.15, FIRST10: 0.1 },
  };
})();
